/* ============================================================
   THE PSALTER

   Septuagint numbering, as the Orthodox Church uses it — one behind
   the Hebrew numbering from Psalm 9 onward. Psalm 50 is "Have mercy
   upon me, O God"; Psalm 90 is "He that dwells in the help of the
   Highest".

   Text: LXX2012 (public domain), the modern revision of Brenton's
   1851 English Septuagint. Footnote and cross-reference markers have
   been stripped; words the translators supplied are kept.

   Only the psalms appointed in this book are included. To add more,
   follow the same shape: PSALMS[n] = [ 'verse', 'verse', ... ]
   ============================================================ */

var PSALMS = {
  3: [
    'O Lord, why are they that afflict me multiplied? many rise up against me.',
    'Many say concerning my soul, There is no deliverance for him in his God. Pause.',
    'But you, O Lord, are my helper: my glory, and the one that lifts up my head.',
    'I cried to the Lord with my voice, and he heard me out of his holy mountain. Pause.',
    'I lay down and slept; I awaked; for the Lord will help me.',
    'I will not be afraid of ten thousands of people, who beset me round about.',
    'Arise, Lord; deliver me, my God: for you have struck all who were without cause my enemies; you have broken the teeth of sinners.',
    'Deliverance is the Lord\'s, and your blessing is upon your people.',
  ],
  5: [
    'Listen to my words, O Lord, attend to my cry.',
    'Attend to the voice of my supplication, my King, and my God: for to you, O Lord, will I pray.',
    'In the morning you shall hear my voice: in the morning will I wait upon you, and will look up.',
    'For you are not a god that desires iniquity; neither shall the worker of wickedness dwell with you.',
    'Neither shall the transgressors continue in your sight: you hate, O Lord, all them that work iniquity.',
    'You will destroy all that speak falsehood: the Lord abhors the bloody and deceitful man.',
    'But I will enter into your house in the multitude of your mercy: I will worship in your fear toward your holy temple.',
    'Lead me, O Lord, in your righteousness because of my enemies; make my way plain before your face.',
    'For there is no truth in their mouth; their heart is vain; their throat is an open sepulchre; with their tongues they have used deceit.',
    'Judge them, O God; let them fail of their counsels: cast them out according to the abundance of their ungodliness; for they have provoked you, O Lord.',
    'But let all that trust on you be glad in you: they shall exult for ever, and you shall dwell among them; and all that love your name shall rejoice in you.',
    'For you, Lord, shall bless the righteous: you have compassed us as with a shield of favor.',
  ],
  16: [
    'Listen, O Lord of my righteousness, attend to my petition; give ear to my prayer not with deceitful lips.',
    'Let my judgment come forth from your presence; let my eyes behold righteousness.',
    'You have tested my heart; you have visited by night; you have tried me as with fire, and unrighteousness has not been found in me: that my mouth shall not speak.',
    'As for the works of men, by the words of your lips I have guarded hard ways.',
    'Direct my steps in your paths, that my steps slip not.',
    'I have cried, for you heard me, O God: incline your ear to me, and listen to my words.',
    'Show the marvels of your mercies, you that save them that hope in you.',
    'Keep me as the apple of the eye from those that resist your right hand: you shall screen me by the covering of your wings,',
    'from the face of the ungodly that have afflicted me: my enemies have compassed about my soul.',
    'They have enclosed their own fat: their mouth has spoken pride.',
    'They have now cast me out and compassed me round about: they have set their eyes to bow them down to the ground.',
    'They laid wait for me as a lion ready for prey, and like a lion\'s whelp dwelling in secret.',
    'Arise, O Lord, prevent them, and cast them down: deliver my soul from the ungodly: your sword,',
    'because of the enemies of your hand: O Lord, destroy them from the earth; scatter them in their life, though their belly has been filled with your hidden : they have been satisfied with uncleanness, and have left the remnant to their babes.',
    'But I shall appear in righteousness before your face: I shall be satisfied when your glory appears.',
  ],
  24: [
    'To you, O Lord, have I lifted up my soul.',
    'O my God, I have trusted in you: let me not be confounded, neither let my enemies laugh me to scorn.',
    'For none of them that wait on you shall in any wise be ashamed: let them be ashamed that transgress without cause.',
    'Show me your ways, O Lord; and teach me your paths.',
    'Lead me in your truth, and teach me: for you are God my Saviour: and I have waited on you all the day.',
    'Remember your compassions, O Lord, and your mercies, for they are from everlasting.',
    'Remember not the sins of my youth, nor of ignorance: remember me according to your mercy, for your goodness\' sake, O Lord.',
    'Good and upright is the Lord: therefore will he instruct sinners in way.',
    'The meek will he guide in judgment: the meek will he teach his ways.',
    'All the ways of the Lord are mercy and truth to them that seek his covenant and his testimonies.',
    'For your name\'s sake, O Lord, do you also be merciful to my sin; for it is great.',
    'Who is the man that fears the Lord? he shall instruct him in the way which he has chosen.',
    'His soul shall dwell in prosperity; and his seed shall inherit the earth.',
    'The Lord is the strength of them that fear him; and his covenant is to manifest to them.',
    'My eyes are continually to the Lord; for he shall draw my feet out of the snare.',
    'Look upon me, and have mercy upon me; for I am an only child and poor.',
    'The afflictions of my heart have been multiplied; deliver me from my distresses.',
    'Look upon my affliction and my trouble; and forgive all my sins.',
    'Look upon my enemies; for they have been multiplied; and they have hated me with unjust hatred.',
    'Keep my soul, and deliver me: let me not be ashamed; for I have hoped in you.',
    'The harmless and upright joined themselves to me: for I waited for you, O Lord.',
    'Deliver Israel, O God, out of all his afflictions.',
  ],
  26: [
    'The Lord is my light and my Saviour; whom shall I fear? the Lord is the defender of my life; of whom shall I be afraid?',
    'When evil-doers drew near against me to eat up my flesh, my persecutors and my enemies, they fainted and fell.',
    'Though an army should set itself in array against me, my heart shall not be afraid: though war should rise up against me, in this am I confident.',
    'One thing have I asked of the Lord, this will I earnestly seek: that I should dwell in the house of the Lord, all the days of my life, that I should behold the fair beauty of the Lord, and survey his temple.',
    'For in the day of my afflictions he hid me in his tabernacle: he sheltered me in the secret of his tabernacle; he set me up on a rock.',
    'And now, behold, he has lifted up my head over my enemies: I went round and offered in his tabernacle the sacrifice of joy; I will sing even sing psalms to the Lord.',
    'Hear, O Lord, my voice which I have uttered aloud: pity me, and listen to me.',
    'My heart said to you, I have diligently sought your face: your face, O Lord, I will seek.',
    'Turn not your face away from me, turn not you away from your servant in anger: be you my helper, forsake me not; and, O God my Saviour, overlook me not.',
    'For my father and my mother have forsaken me, but the Lord has taken me to himself.',
    'Teach me, O Lord, in your way, and guide me in a right path, because of my enemies.',
    'Deliver me not over to the desire of them that afflict me; for unjust witnesses have risen up against me, and injustice has lied within herself.',
    'I believe that I shall see the goodness of the Lord in the land of the living.',
    'Wait on the Lord: be of good courage, and let your heart be strengthened: yes wait on the Lord.',
  ],
  37: [
    'O Lord, rebuke me not in your wrath, neither chasten me in your anger.',
    'For your weapons are fixed in me, and you have pressed your hand heavily upon me.',
    'For there is no health in my flesh because of your anger; there is no peace to my bones because of my sins.',
    'For my transgressions have gone over my head: they have pressed heavily upon me like a weighty burden.',
    'My bruises have become noisome and corrupt, because of my foolishness.',
    'I have been wretched and bowed down continually: I went with a mourning countenance all the day.',
    'For my soul is filled with mockings; and there is no health in my flesh.',
    'I have been afflicted and brought down exceedingly: I have roared for the groaning of my heart.',
    'But all my desire is before you; and my groaning is not hidden from you.',
    'My heart is troubled, my strength has failed me; and the light of my eyes is not with me.',
    'My friends and my neighbors drew near before me, and stood still; and my nearest of kin stood afar off.',
    'While they pressed hard upon me that sought my soul: and they that sought my hurt spoke vanities, and devised deceits all the day.',
    'But I, as a deaf man, heard not; and was as a dumb man not opening his mouth.',
    'And I was as a man that hears not, and who has no reproofs in his mouth.',
    'For I hoped in you, O Lord: you will hear, O Lord my God.',
    'For I said, Lest my enemies rejoice against me: for when my feet were moved, they spoke boastingly against me.',
    'For I am ready for plagues, and my grief is continually before me.',
    'For I will declare my iniquity, and be distressed for my sin.',
    'But my enemies live, and are mightier than I: and they that hate me unjustly are multiplied.',
    'They that reward evil for good slandered me; because I followed righteousness.',
    'Forsake me not, O Lord my God: depart not from me.',
    'Draw near to my help, O Lord of my salvation.',
  ],
  45: [
    'God is our refuge and strength, a help in the afflictions that have come heavily upon us.',
    'Therefore will we not fear when the earth is troubled, and the mountains are removed into the depths of the seas.',
    'Their waters have roared and been troubled, the mountains have been troubled by his might. Pause.',
    'The flowings of the river gladden the city of God: the Most High has sanctified his tabernacle.',
    'God is in the midst of her; she shall not be moved: God shall help her with his countenance.',
    'The nations were troubled, the kingdoms tottered: he uttered his voice, the earth shook.',
    'The Lord of hosts is with us; the God of Jacob is our helper. Pause.',
    'Come, and behold the works of the Lord, what wonders he has achieved on the earth.',
    'Putting an end to wars as for the ends of the earth; he will crush the bow, and break in pieces the weapon, and burn the bucklers with fire.',
    'Be still, and know that I am God: I will be exalted among the nations, I will be exalted in the earth.',
    'The Lord of hosts is with us; the God of Jacob is our helper.',
  ],
  50: [
    'Have mercy upon me, O God, according to your great mercy; and according to the multitude of your compassions blot out my transgression.',
    'Wash me thoroughly from my iniquity, and cleanse me from my sin.',
    'For I am conscious of my iniquity; and my sin is continually before me.',
    'Against you only have I sinned, and done evil before you: that you might be justified in your sayings, and might overcome when you are judged.',
    'For, behold, I was conceived in iniquities, and in sins did my mother conceive me.',
    'For, behold, you love truth: you have manifested to me the secret and hidden things of your wisdom.',
    'You shall sprinkle me with hyssop, and I shall be purified: you shall wash me, and I shall be made whiter than snow.',
    'You shall cause me to hear gladness and joy: the afflicted bones shall rejoice.',
    'Turn away your face from my sins, and blot out all my iniquities.',
    'Create in me a clean heart, O God; and renew a right spirit in my inward parts.',
    'Cast me not away from your presence; and remove not your holy Spirit from me.',
    'Restore to me the joy of your salvation: establish me with your directing Spirit.',
    'will I teach transgressors your ways; and ungodly men shall turn to you.',
    'Deliver me from blood-guiltiness, O God, the God of my salvation: my tongue shall joyfully declare your righteousness.',
    'O Lord, you shall open my lips; and my mouth shall declare your praise.',
    'For if you desired sacrifice, I would have given : you will not take pleasure in whole burnt offerings.',
    'Sacrifice to God is a broken spirit: a broken and humbled heart God will not despise.',
    'Do good, O Lord, to Sion in your good pleasure; and let the walls of Jerusalem be built.',
    'Then shall you be pleased with a sacrifice of righteousness, offering, and whole burnt sacrifices: then shall they offer calves upon your altar.',
  ],
  53: [
    'Save me, O God, by your name, and judge me by your might.',
    'O God, hear my prayer; listen to the words of my mouth.',
    'For strangers have risen up against me, and mighty men have sought my life: they have not set God before them. Pause.',
    'For behold! God assists me; and the Lord is the helper of my soul.',
    'He shall return evil to my enemies; utterly destroy them in your truth.',
    'I will willingly sacrifice to you: I will give thanks to your name, O Lord; for good.',
    'For you have delivered me out of all affliction, and my eye has seen upon my enemies.',
  ],
  54: [
    'Listen, O God, to my prayer; and disregard not my supplication.',
    'Attend to me, and listen to me: I was grieved in my meditation, and troubled;',
    'because of the voice of the enemy, and because of the oppression of the sinner: for they brought iniquity against me, and were wrathfully angry with me.',
    'My heart was troubled within me; and the fear of death fell upon me.',
    'Fear and trembling came upon me, and darkness covered me.',
    'And I said, O that I had wings as of a dove! then would I flee away, and be at rest.',
    'Behold! I have fled afar off, and lodged in the wilderness. Pause.',
    'I waited for him that should deliver me from distress of spirit and tempest.',
    'Destroy, O Lord, and divide their tongues: for I have seen iniquity and gain saying in the city.',
    'Day and night he shall go round about it upon its walls: iniquity and sorrow and unrighteousness in the midst of it;',
    'and usury and craft have not failed from its streets.',
    'For if an enemy had reproached me, I would have endured it; and if one who hated had spoken vauntingly against me, I would have hid myself from him.',
    'But you, O man like minded, my guide, and my acquaintance,',
    'who in companionship with me sweetened food: we walked in the house of God in concord.',
    'Let death come upon them, and let them go down alive into Hades, for iniquity is in their dwellings, in the midst of them.',
    'I cried to God, and the Lord listened to me.',
    'Evening, and morning, and at noon I will declare and make known : and he shall hear my voice.',
    'He shall deliver my soul in peace from them that draw near to me: for they were with me in many.',
    'God shall hear, and bring them low, he that has existed from eternity. Pause. For they suffer no reverse, and they have not feared God.',
    'He has reached forth his hand for retribution; they have profaned his covenant.',
    'They were scattered at the anger of his countenance, and his heart drew near them. His words were smoother than oil, yet are they darts.',
    'Cast your care upon the Lord, and he shall sustain you; he shall never suffer the righteous to be moved.',
    'But you, O God, shall bring them down to the pit of destruction; bloody and crafty men shall not live out half their days; but I will hope in you, O Lord.',
  ],
  62: [
    'O God, my God, I cry to you early; my soul has thirsted for you: how often has my flesh after you, in a barren and trackless and dry land!',
    'Thus have I appeared before you in the sanctuary, that I might see your power and your glory.',
    'For your mercy is better than life: my lips shall praise you.',
    'Thus will I bless you during my life: I will lift up my hands in your name.',
    'Let my soul be filled as with marrow and fatness; and joyful lips shall praise your name.',
    'Forasmuch as I have remembered you on my bed: in the early seasons I have meditated on you.',
    'For you have been my helper, and in the shelter of your wings will I rejoice.',
    'My soul has kept very close behind you: your right hand has upheld me.',
    'But they vainly sought after my soul; they shall go into the lowest parts o the earth.',
    'They shall be delivered up to the power of the sword; they shall be portions for foxes.',
    'But the king shall rejoice in God; every one that swears by him shall be praised; for the mouth of them that speak unjust things has been stopped.',
  ],
  69: [
    'Draw near, O God, to my help.',
    'Let them be ashamed and confounded that seek my soul: let them be turned backward and put to shame, that wish me evil.',
    'Let them that say to me, Aha, aha, be turned back and put to shame immediately.',
    'Let all that seek you exult and be glad in you: and let those that love your salvation say continually, Let God be magnified.',
    'But I am poor and needy; O God, help me: you are my helper and deliverer, O Lord, delay not.',
  ],
  83: [
    'How amiable are your tabernacles, O Lord of hosts!',
    'My soul longs, and faints for the courts of the Lord: my heart and my flesh have exulted in the living god.',
    'Yes, the sparrow has found himself a home, and the turtle-dove a nest for herself, where she may lay her young, your altars, O Lord of hosts, my King, and my God.',
    'Blessed are they that dwell in your house: they will praise you evermore. Pause.',
    'Blessed is the man whose help is of you, O Lord; in his heart he has purposed to go up',
    'the valley of weeping, to the place which he has appointed, for the law-giver will grant blessings.',
    'They shall go from strength to strength: the God of gods shall be seen in Sion.',
    'O Lord God of hosts, hear my prayer: listen, O God of Jacob. Pause.',
    'Behold, O God our defender, and look upon the face of your anointed.',
    'For one day in your courts is better than thousands. I would rather be an abject in the house of God, than dwell in the tents of sinners.',
    'For the Lord loves mercy and truth: God will give grace and glory: the Lord will not withhold good things from them that walk in innocence.',
    'O Lord of hosts, blessed is the man that trusts in you.',
  ],
  84: [
    'O Lord, you have taken pleasure in your land: you have turned back the captivity of Jacob.',
    'You have forgiven your people their transgressions; you have covered all their sins. Pause.',
    'You have caused all your wrath to cease: you have turned from your fierce anger.',
    'Turn us, O God of our salvation, and turn your anger away from us.',
    'Wouldest you be angry with us for ever? or will you continue your wrath from generation to generation?',
    'O God, you will turn and quicken us; and your people shall rejoice in you.',
    'Show us your mercy, O Lord, and grant us your salvation.',
    'I will hear what the Lord God will say concerning me: for he shall speak peace to his people, and to his saints, and to those that turn their heart toward him.',
    'Moreover his salvation is near them that fear him; that glory may dwell in our land.',
    'Mercy and truth are met together: righteousness and peace have kissed.',
    'Truth has sprung out of the earth; and righteousness has looked down from heaven.',
    'For the Lord will give goodness; and our land shall yield her fruit.',
    'Righteousness shall go before him; and shall set his steps in the way.',
  ],
  85: [
    'O Lord, incline your ear, and listen to me; for I am poor and needy.',
    'Preserve my soul, for I am holy; save your servant, O God, who hopes in you.',
    'Pity me, O Lord: for to you will I cry all the day.',
    'Rejoice the soul of your servant: for to you, O Lord, have I lifted up my soul.',
    'For you, O Lord, are kind, and gentle; and plenteous in mercy to all that call upon you.',
    'Give ear to my prayer, o Lord; and attend to the voice of my supplication.',
    'In the day of my trouble I cried to you: for you did hear me.',
    'There is none like to you, O Lord, among the gods; and there are no like to your works.',
    'All nations whom you have made shall come, and shall worship before you, O Lord; and shall glorify your name.',
    'For you are great, and do wonders: you are the only the great God.',
    'Guide me, O Lord, in your way, and I will walk in your truth: let my heart rejoice, that I may fear your name.',
    'I will give you thanks, O Lord my God, with all my heart; and I will glorify your name for ever.',
    'For your mercy is great toward me; and you have delivered my soul from the lowest hell.',
    'O God, transgressors have risen up against me, and an assembly of violent have sought my life; and have not set you before them.',
    'But you, O Lord God, are compassionate and merciful, longsuffering, and abundant in mercy and true.',
    'Look you upon me, and have mercy upon me: give your strength to your servant, and save the son of your handmaid.',
    'Establish with me a token for good; and let them that hate me see and be ashamed; because you, O Lord, have helped me, and comforted me.',
  ],
  87: [
    'O Lord God of my salvation, I have cried by day and in the night before you.',
    'Let my prayer come in before you; incline your ear to my supplication, O Lord.',
    'For my soul is filled with troubles, and my life has drawn near to Hades.',
    'I have been reckoned with them that go down to the pit; I became as a man without help;',
    'free among the dead, as the slain ones cast out, who sleep in the tomb; whom you remember no more; and they are rejected from your hand.',
    'They laid me in the lowest pit, in dark, and in the shadow of death.',
    'Your wrath has pressed heavily upon me, and you have brought upon me all your billows. Pause.',
    'You have removed my acquaintance far from me; they have made me an abomination to themselves; I have been delivered up, and have not gone forth.',
    'My eyes are dimmed from poverty; but I cried to you, O Lord, all the day; I spread forth my hands to you.',
    'Will you work wonders for the dead? or shall physicians raise up, that they shall praise you?',
    'Shall any one declare your mercy in the tomb? and your truth in destruction?',
    'Shall your wonders be known in darkness? and your righteousness in a forgotten land?',
    'But I cried to you, O Lord; and in the morning shall my prayer prevent you.',
    'Therefore, O Lord, do you reject my prayer, turn your face away from me?',
    'I am poor and in troubles from my youth; and having been exalted, I was brought low and into despair.',
    'Your wrath has passed over me; and your terrors have greatly disquieted me.',
    'They compassed me like water; all the day they beset me together.',
    'You have put far from me friend, and my acquaintances because of wretchedness.',
  ],
  89: [
    'Lord, you have been our refuge in all generations.',
    'Before the mountains existed, and the earth and the world were formed, even from age to age, You are.',
    'Turn not man back to low place, whereas you said, Return, you\u2303 sons of men?',
    'For a thousand years in your sight are as the yesterday which is past, and as a watch in the night.',
    'Years shall be vanity to them: let the morning pass away as grass.',
    'In the morning let it flower, and pass away: in the evening let it droop, let it be withered and dried up.',
    'For we have perished in your anger, and in your wrath we have been troubled.',
    'You have set our transgressions before you: our age is in the light of your countenance.',
    'For all our days are gone, and we have passed away in your wrath: our years have spun out their tale as a spider.',
    'the days of our years, in them are seventy years; and if in strength, eighty years: and the greater part of them would be labor and trouble; for weakness overtakes us, and we shall be chastened.',
    'Who knows the power of your wrath?',
    'and to number because of the fear of your wrath? So manifest your right hand, and those that are instructed in wisdom in the heart.',
    'Return, O Lord, how long? and be entreated concerning your servants.',
    'We have been satisfied in the morning with your mercy; and we did exult and rejoice:',
    'let us rejoice in all our days, in return for the days wherein you did afflict us, the years wherein we saw evil.',
    'And look upon your servants, and upon your works; and guide their children.',
    'And let the brightness of the Lord our God be upon us: and do you direct for us the works of our hands.',
  ],
  90: [
    'He that dwells in the help of the Highest, shall sojourn under the shelter of the God of heaven.',
    'He shall say to the Lord, You are my helper and my refuge: my God; I will hope in him.',
    'For he shall deliver you from the snare of the hunters, from troublesome matter.',
    'He shall overshadow you with his shoulders, and you shall trust under his wings: his truth shall cover you with a shield.',
    'You shall not be afraid of terror by night; nor of the arrow flying by day;',
    'of the thing that walks in darkness; of calamity, and the evil spirit at noon-day.',
    'A thousand shall fall at your side, and ten thousand at your right hand; but it shall not come near you.',
    'Only with your eyes shall you observe and see the reward of sinners.',
    'For you, O Lord, are my hope: you, my soul, have made the Most High your refuge.',
    'No evils shall come upon you, and no scourge shall draw near to your dwelling.',
    'For he shall give his angels charge concerning you, to keep you in all your ways.',
    'They shall bear you up on their hands, lest at any time you dash your foot against a stone.',
    'You shall tread on the asp and basilisk: and you shall trample on the lion and dragon.',
    'For he has hoped in me, and I will deliver him: I will protect him, because he has known my name.',
    'He shall call upon me, and I will listen to him: I am with him in affliction; and I will deliver him, and glorify him.',
    'I will satisfy him with length of days, and show him my salvation.',
  ],
  100: [
    'I will sing to you, O Lord, of mercy and judgment; I will sing a psalm,',
    'and I will be wise in a blameless way. When will you come to me? I walked in the innocence of my heart, in the midst of my house.',
    'I have not set before my eyes any unlawful thing; I have hated transgressors.',
    'A perverse heart has not cleaved to me; I have not known an evil man, forasmuch as he turns away from me.',
    'Him that privily speaks against his neighbor, him have I driven from : he that is proud in look and insatiable in heart, \u2014with him I have not eaten.',
    'My eyes upon the faithful of the land, that they may dwell with me: he that walked in a perfect way, the same ministered to me.',
    'The proud doer lived not in the midst of my house; the unjust speaker prospered not in my sight.',
    'Early did I kill all the sinners of the land, that I might destroy out of the city of the Lord all that work iniquity.',
  ],
  102: [
    'Bless the Lord, O my soul; and all within me, his holy name.',
    'Bless the Lord, O my soul, and forget not all his praises:',
    'who forgives all your transgressions, who heals all your diseases;',
    'who redeems your life from corruption; who crowns you with mercy and compassion;',
    'who satisfies your desire with good things: your youth shall be renewed like of the eagle.',
    'The Lord executes mercy and judgment for all that are injured.',
    'He made known his ways to Moses, his will to the children of Israel.',
    'The Lord is compassionate and pitiful, longsuffering, and full of mercy.',
    'He will not be always angry; neither will he be wrathful for ever.',
    'He has not dealt with us according to our sins, nor recompensed us according to our iniquities.',
    'For as the heaven is high above the earth, the Lord has increased his mercy toward them that fear him.',
    'As far as the east is from the west, has he removed our transgressions from us.',
    'As a father pities children, the Lord pities them that fear him.',
    'For he knows our frame: remember that we are dust.',
    'man, his days are as grass; as a flower of the field, so shall he flourish.',
    'For the wind passes over it, and it shall not be; and it shall know its place no more.',
    'But the mercy of the Lord is from generation to generation upon them that fear him, and his righteousness to children\'s children;',
    'to them that keep his covenant, and remember his commandments to do them.',
    'The Lord has prepared his throne in the heaven; and his kingdom rules over all.',
    'Bless the Lord, all you\u2303 his angels, mighty in strength, who perform his bidding, to listen to the voice of his words.',
    'Bless the Lord, all you\u2303 his hosts; ministers of his that do his will.',
    'Bless the Lord, all his works, in every place of his dominion: bless the Lord, O my soul.',
  ],
  103: [
    'Bless the Lord, O my soul. O Lord my God, you are very great; you have clothed yourself with praise and honor:',
    'who do robe yourself with light as with a garment; spreading out the heaven as a curtain.',
    'Who covers his chambers with waters; who makes the clouds his chariot; who walks on the wings of the wind.',
    'Who makes his angels spirits, and his ministers a flaming fire.',
    'Who establishes the earth on her sure foundation: it shall not be moved for ever.',
    'The deep, as it were a garment, is his covering: the waters shall stand on the hills.',
    'At your rebuke they shall flee; at the voice of your thunder they shall be alarmed.',
    'They go up to the mountains, and down to the plains, to the place which you have founded for them.',
    'You have set a bound which they shall not pass, neither shall they turn again to cover the earth.',
    'He sends forth his fountains among the valleys: the waters shall run between the mountains.',
    'They shall give drink to all the wild beasts of the field: the wild asses shall take to their thirst.',
    'By them shall the birds of the sky lodge: they shall utter a voice out of the midst of the rocks.',
    'He waters the mountains from his chambers: the earth shall be satisfied with the fruit of your works.',
    'He makes grass to grow for the cattle, and green herb for the service of men, to bring bread out of the earth;',
    'and wine makes glad the heart of man, to make his face cheerful with oil: and bread strengthens man\'s heart.',
    'The trees of the plain shall be full; the cedars of Libanus which he has planted.',
    'There the sparrows will build their nests; and the house of the heron takes the lead among them.',
    'The high mountains are a refuge for the stags, the rock for the rabbits.',
    'He appointed the moon for seasons: the sun knows his going down.',
    'You did make darkness, and it was night; in it all the wild beasts of the forest will be abroad:',
    'young lions roaring for prey, and to seek meat for themselves from God.',
    'The sun arises, and they shall be gathered together, and shall lie down in their dens.',
    'Man shall go forth to his work, and to his labor till evening.',
    'How great are your works, O Lord! in wisdom have you wrought them all: the earth is filled with your creation.',
    'this great and wide sea: there are things creeping innumerable, small animals and great.',
    'There go the ships; this dragon whom you have made to play in it.',
    'All wait upon you, to give them food in due season.',
    'When you have given them, they will gather; and when you have opened your hand, they shall all be filled with good.',
    'But when you have turned away your face, they shall be troubled: you will take away their breath, and they shall fail, and return to their dust.',
    'You shall send forth your Spirit, and they shall be created; and you shall renew the face of the earth.',
    'Let the glory of the Lord be for ever: the Lord shall rejoice in his works;',
    'who looks upon the earth, and makes it tremble; who touches the mountains, and they smoke.',
    'I will sing to the Lord while I live; I will sing praise to my God while I exist.',
    'Let my meditation be sweet to him: and I will rejoice in the Lord.',
    'Let the sinners fail from off the earth, and transgressors, so that they shall be no more. Bless the Lord, O my soul.',
  ],
  142: [
    'O Lord, attend to my prayer: listen to my supplication in your truth; hear me in your righteousness.',
    'And enter not into judgment with your servant, for in your sight shall no living be justified.',
    'For the enemy has persecuted my soul; he has brought my life down to the ground; he has made me to dwell in a dark, as those that have been long dead.',
    'Therefore my spirit was grieved in me; my heart was troubled within me.',
    'I remembered the days of old; and I meditated on all your doings:, I meditated on the works of your hands.',
    'I spread forth my hands to you; my soul for you, as a dry land. Pause.',
    'Hear me speedily, O Lord; my spirit has failed; turn not away your face from me, else I shall be like to them that go down to the pit.',
    'Cause me to hear your mercy in the morning; for I have hoped in you; make known to me, O Lord, the way wherein I should walk; for I have lifted up my soul to you.',
    'Deliver me from my enemies, O Lord; for I have fled to you for refuge.',
    'Teach me to do your will; for you are my God; your good Spirit shall guide me in the straight.',
    'You shall quicken me, O Lord, for your name\'s sake; in your righteousness you shall bring my soul out of affliction.',
    'And in your mercy you will destroy my enemies, and will destroy all those that afflict my soul; for I am your servant.',
  ],
  145: [
    'My soul, praise the Lord.',
    'While I live will I praise the Lord: I will sing praises to my God as long as I exist.',
    'Trust not in princes, nor in the children of men, in whom there is no safety.',
    'His breath shall go forth, and he shall return to his earth; in that day all his thoughts shall perish.',
    'Blessed is he whose helper is the God of Jacob, whose hope is in the Lord his God:',
    'who made heaven, and earth, the sea, and all things in them: who keeps truth for ever:',
    'who executes judgment for the wronged: who gives food to the hungry. The Lord looses the fettered ones:',
    'the Lord gives wisdom to the blind: The Lord sets up the broken down: the Lord loves the righteous: the Lord preserves the strangers;',
    'he will relieve the orphan and widow: but will utterly remove the way of sinners.',
    'The Lord shall reign for ever, your God, O Sion, to all generations.',
  ],
};

var PSALM_TITLES = {
 "3": "Psalm 3",
 "5": "Psalm 5",
 "16": "Psalm 16",
 "24": "Psalm 24",
 "26": "Psalm 26",
 "37": "Psalm 37",
 "45": "Psalm 45",
 "50": "Psalm 50",
 "53": "Psalm 53",
 "54": "Psalm 54",
 "62": "Psalm 62",
 "69": "Psalm 69",
 "83": "Psalm 83",
 "84": "Psalm 84",
 "85": "Psalm 85",
 "87": "Psalm 87",
 "89": "Psalm 89",
 "90": "Psalm 90",
 "100": "Psalm 100",
 "102": "Psalm 102",
 "103": "Psalm 103",
 "142": "Psalm 142",
 "145": "Psalm 145"
};

/* Build a readable block list for one psalm. */
function psalmBlocks(n, opts){
  opts = opts || {};
  var vv = PSALMS[n];
  if(!vv) return [R('Psalm ' + n + ' is not included in this book.')];
  var out = [];
  if(!opts.noHeading) out.push(H('Psalm ' + n));
  for(var i = 0; i < vv.length; i++) out.push(V(vv[i]));
  return out;
}
